on: [push]
name: Validate JSON schema
jobs:
  validate_configurations:
    name: Validate configurations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Validate any json file
        uses: mcandeia/json-schema-validator@v1.0.0
        with:
          token: ${{ secrets.GH_ACTIONS_ORGANIZATION_TOKEN }}
          send_comment: true
          clear_comments: true